name: Command Dispatch for PR events
on:
  issue_comment:
    types: [created]

# Enables maintainers with "write" permission to trigger jobs on external pull requests.

jobs:
  command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch command
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          permission: write
          issue-type: pull-request
          repository: pulumi/pulumi
          commands: |
            run-acceptance-tests
            run-docs-gen
            run-codegen
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '/rebase') || 
        contains(github.event.comment.body, '/autosquash')
      )
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@50007412be906b9cc222db3dfc469f325031f1b2
        with:
          autosquash: ${{ contains(github.event.comment.body, '/autosquash') || contains(github.event.comment.body, '/rebase-autosquash') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

